title: "Bulma: a modern CSS framework based on Flexbox"
description: Bulma is an open source CSS framework based on Flexbox and built with Sass.
            It's 100% responsive, fully modular, and available for free.
favicon: favicons/favicon.ico
