title: 'Bulma: a modern CSS framework based on Flexbox'
description: Bulma is an open source CSS framework based on Flexbox and built with Sass.
  It's 100% responsive, fully modular, and available for free.
favicon: favicons/favicon.ico
project_title: Bulma
software_license:
  name: MIT
  url: https://opensource.org/licenses/mit-license.php
website_license:
  name: CC BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/
author:
  name: Jeremy Thomas
  website: https://jgthms.com
