title: "Bulma: a modern CSS framework based on Flexbox"
description: Bulma is an open source CSS framework based on Flexbox and built with Sass.
  It's 100% responsive, fully modular, and available for free.
favicon: favicons/favicon.ico

sidebar:
  - label: Overview
    is_active: true
    entries:
      - label: Start
        href: /documentation_overview_start.html
      - label: Classes
        href: /documentation_overview_start.html
      - label: Modularity
        href: /documentation_overview_start.html
      - label: Responsiveness
        href: /documentation_overview_start.html
      - label: Colors
        href: /documentation_overview_start.html
      - label: Functions
        href: /documentation_overview_start.html
      - label: Mixins
        href: /documentation_overview_start.html
  - label: Customize
  - label: Modifiers
  - label: Columns
    is_new: true
  - label: Layout
  - label: Form
  - label: Elements
  - label: Components

footer:
  links:
    columns:
    # Column 1
    - groups:
      - label: Home
        href: https://bulma.io
      - label: Blog
        href: /blog.html
        more:
          label: View all posts
          href: /all_blog.html
        entries:
        - label: Automatic variables docs
          href: /1.html
        - label: Migrating to v0.7.0
          href: /1.html
        - label: Website redesign
          href: /1.html
        - label: Font Awesome 5
          href: /1.html

    # Column 2
    - groups:
      - label: Documentation
        href: /documentation.html
        entries:
        - label: Overview
          href: /1.html
        - label: Customize
          href: /1.html
        - label: Modifiers
          href: /1.html
        - label: Columns
          href: /1.html
        - label: Layout
          href: /1.html
        - label: Form
          href: /1.html
        - label: Elements
          href: /1.html
        - label: Components
          href: /1.html

    # Column 3
    - fullsize: true
      groups:
      - label: More
        href: /documentation.html
        entries:
        - label: Expo
          icon: star
          accent: star
          subtitle: Official Bulma showcase
          href: /1.html
        - label: Love
          icon: heart
          accent: danger
          subtitle: Fans of Bulma around the world
          href: /1.html
        - label: Bulma start
          icon: rocket
          accent: success
          subtitle: A tiny npm package to get started
          href: /1.html
        - label: Made with Bulma
          icon: certificate
          accent: primary
          subtitle: The official community badge
          href: /1.html
        - label: Coming from Bootstrap
          icon: exchange-alt
          accent: bootstrap
          subtitle: See how Bulma is an alternative to Bootstrap
          href: /1.html
        - label: Patreon backers
          icon: patreon
          accent: patreon
          subtitle: Everyone who is supporting Bulma
          href: /1.html
        - label: Bulma extensions
          icon: plug
          accent: orange
          subtitle: Side projects to enhance Bulma
          href: /1.html
